### ISSUE TITLE
Manger des frites 🍟

### ISSUE THREAD

**Issue by adriengou** [digifab-dev/TrombiFab#18]
🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟🍟 Elon Musk

**Comment by AudreyCa** [comment]
🤣

**Comment by ghost** [comment]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOh

**Comment by ManuHell74** [comment]
Ouaine tou tri ?

**Comment by ImaneQ** [comment]
Etape 1: éplucher les pommes de terre

**Comment by AudreyCa** [comment]
Etape 2 : Laver les pommes de terre
