### ISSUE TITLE
erreur d'affichage du nombre de pays

### ISSUE THREAD

**Issue by ghost** [digifab-dev/TrombiFab#22]

**Comment by krimokiss** [comment]
un ptit indice : removeDuplicateCountryNames . Normalement avec ça, vous êtes en mesure d'aller au bon endroit pour chercher.
Une seule ligne à modifié et le tour est dans le sac.

**Comment by krimokiss** [comment]
Le même pays écrit en majuscule ou en minuscule est inscrit 2 fois au lieu d'une. Voilà un autre tips pour mieux axer les recherches.
